version: "3.8"
services:
  shortener_service:
    build: .
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: debug
      PORT: "8080"
      MONGO_CONN_STR: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
